name: Update CDC timeseries 2

on: workflow_dispatch
 

defaults:
  run:
     working-directory: timeseries/

jobs:
  update:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/cache@v2
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
        - name: Use Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Run script
          run: |
             cd ../ && python timeseries/make_timeseries.py vaccination_county.json vaccination_county_condensed_data > timeseries/county_vaccinations_timeseries.csv
        - name: Commit
          if: github.ref == 'refs/heads/main'
          uses: EndBug/add-and-commit@v5
          with:
            message: Updating timeseries
            add: 'timeseries/county_vaccinations_timeseries.csv'
            author_name: GitHub Actions
            author_email: actions@github.com
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
