name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_trends_data | jq . > vaccination_trends.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

import json
import csv
"""
# Copyright (c) 2020 Aquafortis
# https://github.com/Aquafortis/json-csv-converter
# $ python3 jsontocsv.py
"""
class JsonCsv(object):

    def json_to_csv(self):

        jsonfile = open("vaccination_trends.json", "r")
        data = json.load(jsonfile)
        jsonfile.close()
        csvfile = open("output.csv", "w")
        poetize = csv.writer(csvfile)
        poetize.writerow(data[0].keys())
        for row in data:
            poetize.writerow(row.values())
        csvfile.close()

JsonCsv().json_to_csv()

