version: 2
jobs:
  fetch_and_commit:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            cp vaccine_distribution.csv
            curl -o vaccine_distribution.csv "https://www.cdc.gov/coronavirus/2019-ncov/json/covid-vaccines-data.csv"
            git add vaccine_distribution.csv
            git config --global user.email "treebot@example.com"
            git config --global user.name "Treebot"
            sudo pip install -r requirements.txt
              git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/bhrenton/cdc-vaccination-data main \
              || true

workflows:
  version: 2
  build:
    jobs:
      - fetch_and_commit
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - fetch_and_commit
